# Generated by Django 5.0.7 on 2024-09-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(blank=True, max_length=200)),
                ('college_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college.college')),
            ],
        ),
    ]
